#!/bin/bash
#############################################################################
# Apt Proxy Discover                                                        #
# Date: 17/01/2014                                                          #
# Version: 0.4.1                                                            #
# Author: José Miguel Silva Caldeira                                        #
# Mail: miguel@ncdc.pt                                                      #
# Web: http://www.ncdc.pt                                                   #
# Many thanks to all who tested this script with me, you know who you are.  #
#############################################################################

#############################################################################
#                                  ChangeLog                                #
#############################################################################
# 2015-7-8 - 0.4.0                                                          #
# Derived from the fact that this software is dependent on the PHP to work. #
# I decided to convert the package to use only bash.                        #
# 2015-7-22 - 0.4.1                                                         #
# Ignore Meta entries, this problem was that a thorough search was made in  #
# all ips, since the interface is not configured at the time. This consumes #
# processor because you have to go through all the possible ips in 32bit,   #
# 4 octets.                                                                 #
#############################################################################

export LANG=C

# Let's ignore meta entries
if [ "$ADDRFAM" = "meta" ]; then
    exit 0
fi

# If this interface is the loopback, exiting
if [[ "$IFACE" == "lo" ]]; then
	exit
fi

time_start=$(date +%s%3N)

is_valid_mask() {
	if [[ -z "$1" ]]; then
		return 1
	fi
	if [[ $1 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
		local mask=$(grep -E -q '^(254|252|248|240|224|192|128)\.0\.0\.0|255\.(254|252|248|240|224|192|128|0)\.0\.0|255\.255\.(254|252|248|240|224|192|128|0)\.0|255\.255\.255\.(254|252|248|240|224|192|128|0)' <<< "$1" && echo 0 || echo 1)
		if [[ $mask -eq 0 ]]; then
			return 0
		fi
	fi
	return 1
}

mask2cidr() {
	bits=0
	local IFS=.
	for octet in $1 ; do
		case $octet in
			255) let bits+=8;;
			254) let bits+=7;;
			252) let bits+=6;;
			248) let bits+=5;;
			240) let bits+=4;;
			224) let bits+=3;;
			192) let bits+=2;;
			128) let bits+=1;;
			0);;
		esac
	done
	echo "$bits"
	return 0
}

ip2long() {
	local IFS=. 
	read -a a1 <<< "$1"
	echo "$((${a1[0]}*16777216 + ${a1[1]}*65536 + ${a1[2]}*256 + ${a1[3]}))"
	return 0
}

long2ip() {
	echo "$(($1 / 16777216)).$(($(($1 % 16777216)) / 65536)).$(($(($1 % 65536)) / 256)).$(($1 % 256))"
	return 0
}

little_endian_hexadecimal2ip(){
	a1=()
	i=0
	while read -r -n2 a1[i]; do
		((++i))
	done <<< "$1"
	echo "$((0x${a1[3]})).$((0x${a1[2]})).$((0x${a1[1]})).$((0x${a1[0]}))"
	return 0
}

networkaddress(){
	local IFS=.
	read -a a1 <<< "$1"
	read -a a2 <<< "$2"
	echo "$((${a1[0]} & ${a2[1]})).$((${a1[1]} & ${a2[1]})).$((${a1[2]} & ${a2[2]})).$((${a1[3]} & ${a2[3]}))"
}

get_interface_mask(){
	while read -a a1; do
		if [[ "${a1[0]}" == "$1" ]] && \
		[[ "${a1[2]}" == "00000000" ]] &&\
		[[ "${a1[1]}" != "0000FEA9" ]]; then
			echo $(little_endian_hexadecimal2ip "${a1[7]}")
			return 0
		fi
	done < /proc/net/route
	return 1
}

get_interface_network(){
	while read -a a1; do
		if [[ "${a1[0]}" == "$1" ]] && \
		[[ "${a1[2]}" == "00000000" ]] && \
		[[ "${a1[1]}" != "0000FEA9" ]]; then
			echo $(little_endian_hexadecimal2ip "${a1[1]}")
			return 0
		fi
	done < /proc/net/route
	return 1
}
read_http_response(){
	local request=$(timeout -s KILL 0.5 wget --connect-timeout=1 --timeout=1 --spider -S http://$1:3142 2>&1 | grep 'HTTP/')
	read -a a1 <<< "$request"
	if [[ "${a1[1]}" == "200" ]] || [[ "${a1[1]}" == "404" ]]; then
		return 0;
	fi
	return 1;
}

old_proxy_existe(){
	old_proxy_ip=$(grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' /etc/apt/apt.conf.d/01proxy)
	if [[ -z $old_proxy_ip ]]; then
		 return 1;
	fi
	read_http_response "$old_proxy_ip"
	if [[ $? == 0 ]]; then
		return 0
	fi
	return 1
}

proxy_existe(){
	#echo $1 >> /home/miguel/apt_p
	read_http_response "$1"
	if [[ $? == 0 ]]; then
		configure_proxy "$1"
		return 0
	fi
	return 1
}

check_initial_ips(){
	for (( x=0; x < $initial_ips_num; x++ )); do
		proxy_existe $(long2ip $(($firstip + $x)))
		if [[ $? == 0 ]]; then
			return 0;
		fi
	done
	return 1;
}

check_between_ips(){
	for (( x=$(($initial_ips_num)); x < $(($valid_ips_num-$initial_ips_num)); x++ )); do
		proxy_existe $(long2ip $(($firstip + $x)))
		if [[ $? == 0 ]]; then
			return 0;
		fi
	done
	return 1;
}

check_last_ips(){
	for (( x=$(($valid_ips_num-1)); x > $(($valid_ips_num - 1 - $initial_ips_num)); x-- )); do
		proxy_existe $(long2ip $(($firstip + $x)))
		if [[ $? == 0 ]]; then
			return 0;
		fi
	done
	return 1;
}

get_default_gatway_ip(){
	while read -a a1; do
		if [[ "${a1[1]}" == "00000000" ]] && \
		[[ "${a1[7]}" == "00000000" ]]; then
			echo $(little_endian_hexadecimal2ip "${a1[2]}")
			return 0
		fi
	done < /proc/net/route
	return 1
}

get_default_gateway_interface(){
	while read -a a1; do
		if [[ "${a1[1]}" == "00000000" ]] &&\
		[[ "${a1[7]}" == "00000000" ]]; then
			echo "${a1[0]}"
			return 0
		fi
	done < /proc/net/route
	return 1
}

notify_user(){
	while read -r line; do
		read -a a1 <<< "$line"
		if [[ ("${a1[1]}" == ":0" ||  "${a1[1]}" == "tty7") && ("${a1[5]}" == "?" ||  "${a1[5]}" == "old") ]]; then
			user="${a1[0]}"
			break;
		fi
	done <<< "$(who -u)"

	if [[ -z $user ]]; then
		 return 1;
	fi

	user_procs=$(pgrep -u $user)
	for proc in $user_procs; do
		unset DISPLAY
		unset XAUTHORITY 
		unset DBUS_SESSION_BUS_ADDRESS

		DISPLAY=$(grep -az ^DISPLAY= "/proc/$proc/environ"  | cut -d '=' -f 2)
		XAUTHORITY=$(grep -az ^XAUTHORITY= "/proc/$proc/environ"  | cut -d '=' -f 2)
		DBUS_SESSION_BUS_ADDRESS=$(grep -az ^DBUS_SESSION_BUS_ADDRESS= "/proc/$proc/environ"  | cut -d '=' -f 2)

		if [[ $DISPLAY  && $XAUTHORITY && $DBUS_SESSION_BUS_ADDRESS ]]; then
			export $(grep -az ^DISPLAY= "/proc/$proc/environ")
			export $(grep -az ^XAUTHORITY= "/proc/$proc/environ")
			export $(grep -az ^DBUS_SESSION_BUS_ADDRESS= "/proc/$proc/environ")

			su "$user" -c 'notify-send "APT Proxy Discovery" "Foi encontrado um APT Proxy nesta rede.\nO seu sistema foi configurado para usa-lo!" -i info'

			break
		fi
	done
}

configure_proxy(){
	echo "# Não edite este ficheiro manualmente, este ficheiro é configurado" > /etc/apt/apt.conf.d/01proxy
	echo "# pelo apt-proxy-discovery." >> /etc/apt/apt.conf.d/01proxy
	echo "#" >> /etc/apt/apt.conf.d/01proxy
	echo "# O apt-proxy foi encontrado em \"$(($(date +%s%3N) - $time_start))\" milisegundos." >> /etc/apt/apt.conf.d/01proxy
	echo "Acquire::http{ Proxy \"http://$1:3142\";};" >> /etc/apt/apt.conf.d/01proxy
	notify_user
}

proxy_not_found() {
	old_proxy_existe
	if [[ $? == 1 ]]; then
		echo "# Não edite este ficheiro manualmente, este ficheiro é configurado" > /etc/apt/apt.conf.d/01proxy
		echo "# pelo apt-proxy-discovery." >> /etc/apt/apt.conf.d/01proxy
		echo "#" >> /etc/apt/apt.conf.d/01proxy
		echo "# Não foi possível achar um apt-proxy nesta rede!" >> /etc/apt/apt.conf.d/01proxy
	fi
	exit
}

# if interface goes up
if [[ $PHASE == "post-up" ]]; then

	# if a proxy existe we are fine
	# and exit
	old_proxy_existe
	if [[ $? == 0 ]]; then
		exit
	fi

	# I will try the router, to test if it has a
	# apt-proxy-cache running
	# Test first HOP / the router of network
	proxy_existe $(get_default_gatway_ip)
	if [[ $? == 0 ]]; then
		exit
	fi
	# The router have not the apt-proxy-cache running

	# I will try the next router, to test if it has a
	# apt-proxy-cache running
	# Test second HOP / the router of network

	# Try find the router IP with traceroute command
	if which traceroute >/dev/null; then
		tracer=$(traceroute -n -m 2  8.8.8.8 | grep -e "^ 2")
		read -a a1 <<< "$tracer"
		proxy_existe "${a1[1]}"
		if [[ $? == 0 ]]; then
			exit
		fi
	# Try find the router IP with tracepath command
	elif which tracepath >/dev/null; then
		tracer=$(tracepath -n -m 2  8.8.8.8  | grep -e "^ 2:")
		read -a a1 <<< "$tracer"
		proxy_existe "${a1[1]}"
		if [[ $? == 0 ]]; then
			exit
		fi
	fi
	# The router of the next HOP have not the apt-proxy running

	# I need scan all the network to see if some machine have the
	# apt-proxy-cache running on it.
	# It is slow but, let's do it.

	# Collect the necessary information.
	initial_ips_num=5;
 	network=$(get_interface_network  "$IFACE")
	netmask=$(get_interface_mask "$IFACE")
	firstip=$(($(ip2long $network) + 1))
	valid_ips_num=$(($((1 << $((32 - $(mask2cidr $netmask))))) - 1))

	if [[ $(($initial_ips_num * 3)) -lt $valid_ips_num ]]; then
		between_ips_stat=true
		last_ips_stat=true
	else
		initial_ips_num=$valid_ips_num
	fi

	# Check the first ips.
	check_initial_ips
	if [[ $? == 0 ]]; then
		exit
	fi

	# Check out the latest ips.
	if [[ $last_ips_stat ]]; then
		check_last_ips
		if [[ $? == 0 ]]; then
			exit
		fi
	fi

	# Check intermediate ips.
	if [[ $between_ips_stat ]]; then
		check_between_ips
		if [[ $? == 0 ]]; then
			exit
		fi
	fi

	# Sorry I can't find the apt-proxy-cache in this network
	proxy_not_found

# if interface goes down
else
	#/etc/network/if-post-down.d/
	old_proxy_existe
	if [[ $? == 1 ]]; then
		echo "# Não edite este ficheiro manualmente, este ficheiro é configurado" > /etc/apt/apt.conf.d/01proxy
		echo "# pelo apt-proxy-discovery." >> /etc/apt/apt.conf.d/01proxy
		echo "#" >> /etc/apt/apt.conf.d/01proxy
		echo "# Foi removida a configuração do apt-proxy." >> /etc/apt/apt.conf.d/01proxy
	fi
fi

exit
